-- 춘대학교 교육시스템 TABLE 만들기 (미완성)
-- > 해결해야할 일들 : 복합키해결x, 실행x

-- 1.'학과' 테이블 (TB_DEPARTMENT) 생성
CREATE TABLE TB_DEPARTMENT(
    DEPARTMENT_NO VARCHAR2(10) PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(20) NOT NULL,
    CATEGORY VARCHAR2(20),
    OPEN_YN CHAR(1),
    CAPACITY NUMBER );


-- 2.'학생' 테이블 (TB_STUDENT) 생성
CREATE TABLE TB_STUDENT(
    STUDENT_NO VARCHAR2(10) CONSTRAINT STUDENT_NO PRIMARY KEY,
    DEPARTMENT_NO VARCHAR2(10) CONSTRAINT DEPARTMENT_NO_FK 
                    REFERENCES TB_DEPARTMENT(DEPARTMENT_NO),
    STUDENT_NAME VARCHAR2(30) NOT NULL,
    STUDENT_SSN VARCHAR2(14),
    STUDNET_ADDRESS VARCHAR2(100),
    ENTRANCE_DATE DATE,
    ABSENCE_YN CHAR(1),
    COACH_PROFESSOR_NO VARCHAR2(10) CONSTRAINT COACH_PROFESSOR_NO_FK
                REFERENCES TB_PROFESSOR(COACH_PROFESSOR_NO)
);


-- 3.'과목' 테이블 (TB_CLASS) 생성
CREATE TABLE TB_CLASS(
    CLASS_NO VARCHAR2(10) PRIMARY KEY,
    DEPARTMENT_NO VARCHAR2(10) CONSTRAINT DEPARTMENT_NO_FK
            REFERENCES TB_DEPARTMENT(DEPARTMENT_NO),
    PREATTENDING_CLASS_NO VARCHAR(10),
    CLASS_NAME VARCHAR(30) NOT NULL,
    CALSS_TYPE VARCHAR2(10)
);

-- 4.'과목 교수' 테이블(TB_CLASS_PROFESSOR) 생성
CREATE TABLE TB_CLASS_PROFESSOR(
    CLASS_NO VARCHAR2(10) PRIMARY KEY,
    CLASS_NO VARCHAR2(10) CONSTRAINT CLASS_NO_FK
            REFERENCES TB_CLASS_PROFESSOR(TB_CLASS),
    PROFESSOR_NO VARCHAR2(10) PRIMARY KEY,
    PROFESSOR_NO VARCHAR2(10) CONSTRAINT PROFESSOR_NO_FK
            REFERENCES TB_PROFESSOR(PROFESSOR_NO)
);

-- 5.'교수' 테이블(TB_PROFESSOR) 생성
CREATE TABLE TB_PROFESSOR(
    PROFESSOR_NO VARCHAR2(10) PRIMARY KEY,
    PROFESSOR_NAME VARCHAR(30) NOT NULL,
    PROFESSOR_SSN VARCHAR(14),
    PROFESSOR_ADDRESS VARCHAR2(100),
    DEPARTMENT_NO VARCHAR(10) CONSTRAINT DEPARTMENT_NO_FK
            REFERENCES TB_DEPARTMENT(DEPARTMENT_NO)
);

-- 6.'성적' 테이블(TB_GRADE) 생성
CREATE TABLE TB_GRADE(
    TERM_NO VARCHAR(10) PRIMARY KEY,
    CLASS_NO VARCHAR2(10) PRIMARY KEY,
    CLASS_NO VARCHAR2(10) CONSTRAINT CLASS_NO_FK
            REFERENCES TB_CLASS(CLASS_NO),
    STUDENT_NO VARCHAR2(10) PRIMARY KEY,
    STUDENT_NO VARCHAR2(10) CONSTRAINT STUDENT_NO_FK
            REFERENCES TB_STUDENT(STUDENT_NO),
    POINT NUMBER(3,2)
);

